apiVersion: v1
kind: Job
metadata:
  labels: 
    app: myapp
    type: API
  spec: 
    containers: 
      - name: Ivan
      image: slika:1.0
      command: ["python", "main.py"]
      restartPolicy: OnFailure